# Generated by Django 4.2.23 on 2025-12-15 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("construction", "0026_project_gradient_primary_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        help_text="نوع ارائه\u200cدهنده LLM (مثل OpenAI, Anthropic, ...)",
                        max_length=50,
                        verbose_name="ارائه\u200cدهنده LLM",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        help_text="نام مدل LLM استفاده شده (مثل GPT-4, Claude-3, ...)",
                        max_length=200,
                        verbose_name="مدل LLM",
                    ),
                ),
                (
                    "user_message",
                    models.TextField(
                        help_text="سوال یا پیام ارسالی توسط کاربر",
                        verbose_name="پیام کاربر",
                    ),
                ),
                (
                    "assistant_response",
                    models.TextField(
                        help_text="پاسخ تولید شده توسط دستیار هوشمند",
                        verbose_name="پاسخ دستیار",
                    ),
                ),
                (
                    "tools_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="لیست ابزارهایی که در این چت استفاده شده\u200cاند (به صورت JSON)",
                        verbose_name="ابزارهای استفاده شده",
                    ),
                ),
                (
                    "tools_count",
                    models.IntegerField(
                        default=0,
                        help_text="تعداد کل ابزارهای استفاده شده",
                        verbose_name="تعداد ابزارها",
                    ),
                ),
                (
                    "input_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="تعداد توکن\u200cهای ورودی مصرف شده",
                        verbose_name="توکن\u200cهای ورودی",
                    ),
                ),
                (
                    "output_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="تعداد توکن\u200cهای خروجی تولید شده",
                        verbose_name="توکن\u200cهای خروجی",
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="مجموع توکن\u200cهای مصرف شده",
                        verbose_name="مجموع توکن\u200cها",
                    ),
                ),
                (
                    "cached_tokens",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="تعداد توکن\u200cهای کش شده (در صورت پشتیبانی)",
                        null=True,
                        verbose_name="توکن\u200cهای کش شده",
                    ),
                ),
                (
                    "reasoning_tokens",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="تعداد توکن\u200cهای استدلال (در صورت پشتیبانی)",
                        null=True,
                        verbose_name="توکن\u200cهای استدلال",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        help_text="مدت زمان لازم برای تولید پاسخ (به ثانیه)",
                        verbose_name="مدت زمان اجرا (ثانیه)",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="آیا چت با موفقیت انجام شده است؟",
                        verbose_name="موفقیت",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="پیام خطا در صورت بروز مشکل",
                        null=True,
                        verbose_name="پیام خطا",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True,
                        help_text="زمان ایجاد این رکورد",
                        verbose_name="تاریخ ایجاد",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="زمان آخرین به\u200cروزرسانی",
                        verbose_name="تاریخ به\u200cروزرسانی",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="پروژه مرتبط با این چت (در صورت وجود)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_logs",
                        to="construction.project",
                        verbose_name="پروژه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="کاربری که این چت را انجام داده است",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ چت",
                "verbose_name_plural": "لاگ\u200cهای چت",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="assistant_c_created_0d88dc_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="assistant_c_user_id_aaca49_idx",
                    ),
                    models.Index(
                        fields=["project", "-created_at"],
                        name="assistant_c_project_4b50aa_idx",
                    ),
                    models.Index(
                        fields=["llm_provider", "-created_at"],
                        name="assistant_c_llm_pro_7fe11e_idx",
                    ),
                ],
            },
        ),
    ]
