# Generated by Django 4.2.23 on 2025-09-02 20:29

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام بک\u200cآپ"),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("manual", "دستی"),
                            ("automatic", "خودکار"),
                            ("scheduled", "زمان\u200cبندی شده"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="نوع بک\u200cآپ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("running", "در حال اجرا"),
                            ("completed", "تکمیل شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "completed_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تکمیل"
                    ),
                ),
                (
                    "projects_count",
                    models.IntegerField(default=0, verbose_name="تعداد پروژه\u200cها"),
                ),
                (
                    "investors_count",
                    models.IntegerField(
                        default=0, verbose_name="تعداد سرمایه\u200cگذاران"
                    ),
                ),
                (
                    "periods_count",
                    models.IntegerField(default=0, verbose_name="تعداد دوره\u200cها"),
                ),
                (
                    "transactions_count",
                    models.IntegerField(default=0, verbose_name="تعداد تراکنش\u200cها"),
                ),
                (
                    "units_count",
                    models.IntegerField(default=0, verbose_name="تعداد واحدها"),
                ),
                (
                    "total_records",
                    models.IntegerField(default=0, verbose_name="کل رکوردها"),
                ),
                (
                    "file_size_kb",
                    models.FloatField(default=0, verbose_name="حجم فایل (KB)"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="مسیر فایل"),
                ),
                (
                    "success_message",
                    models.TextField(blank=True, verbose_name="پیام موفقیت"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="پیام خطا"),
                ),
                (
                    "include_media",
                    models.BooleanField(
                        default=False, verbose_name="شامل فایل\u200cهای رسانه"
                    ),
                ),
                (
                    "compression_enabled",
                    models.BooleanField(
                        default=True, verbose_name="فشرده\u200cسازی فعال"
                    ),
                ),
            ],
            options={
                "verbose_name": "رکورد بک\u200cآپ",
                "verbose_name_plural": "رکوردهای بک\u200cآپ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_backup_enabled",
                    models.BooleanField(
                        default=False, verbose_name="بک\u200cآپ خودکار فعال"
                    ),
                ),
                (
                    "auto_backup_interval",
                    models.IntegerField(
                        default=24, verbose_name="فاصله بک\u200cآپ خودکار (ساعت)"
                    ),
                ),
                (
                    "auto_backup_time",
                    models.TimeField(
                        default="02:00", verbose_name="زمان بک\u200cآپ خودکار"
                    ),
                ),
                (
                    "max_backups",
                    models.IntegerField(
                        default=10, verbose_name="حداکثر تعداد بک\u200cآپ\u200cها"
                    ),
                ),
                (
                    "auto_cleanup_enabled",
                    models.BooleanField(
                        default=True, verbose_name="پاک\u200cسازی خودکار فعال"
                    ),
                ),
                (
                    "cleanup_after_days",
                    models.IntegerField(
                        default=30, verbose_name="پاک\u200cسازی بعد از (روز)"
                    ),
                ),
                (
                    "compression_enabled",
                    models.BooleanField(
                        default=True, verbose_name="فشرده\u200cسازی فعال"
                    ),
                ),
                (
                    "include_media_files",
                    models.BooleanField(
                        default=False, verbose_name="شامل فایل\u200cهای رسانه"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=False, verbose_name="اعلان\u200cهای ایمیل"
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="ایمیل اعلان\u200cها"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات بک\u200cآپ",
                "verbose_name_plural": "تنظیمات بک\u200cآپ",
            },
        ),
    ]
