# Generated by Django 4.2.23 on 2025-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprecord",
            name="expenses_count",
            field=models.IntegerField(default=0, verbose_name="تعداد هزینه\u200cها"),
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="interest_rates_count",
            field=models.IntegerField(default=0, verbose_name="تعداد نرخ\u200cهای سود"),
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="sales_count",
            field=models.IntegerField(default=0, verbose_name="تعداد فروش\u200cها"),
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="user_profiles_count",
            field=models.IntegerField(
                default=0, verbose_name="تعداد پروفایل\u200cهای کاربری"
            ),
        ),
    ]
