# Generated by Django 4.2.23 on 2025-12-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0002_backuprecord_expenses_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprecord",
            name="petty_cash_transactions_count",
            field=models.IntegerField(
                default=0, verbose_name="تعداد تراکنش\u200cهای تنخواه"
            ),
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="unit_specific_expenses_count",
            field=models.IntegerField(
                default=0, verbose_name="تعداد هزینه\u200cهای اختصاصی واحد"
            ),
        ),
    ]
