# Generated by Django 4.2.23 on 2025-08-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "سرمایه\u200cگذار",
                "verbose_name_plural": "سرمایه\u200cگذاران",
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, verbose_name="عنوان دوره")),
                ("year", models.IntegerField(verbose_name="سال شمسی")),
                ("month_number", models.IntegerField(verbose_name="شماره ماه")),
                ("month_name", models.CharField(max_length=20, verbose_name="نام ماه")),
                ("weight", models.IntegerField(verbose_name="وزن دوره")),
                ("start_date_shamsi", models.DateField(verbose_name="تاریخ شروع شمسی")),
                ("end_date_shamsi", models.DateField(verbose_name="تاریخ پایان شمسی")),
                (
                    "start_date_gregorian",
                    models.DateField(verbose_name="تاریخ شروع میلادی"),
                ),
                (
                    "end_date_gregorian",
                    models.DateField(verbose_name="تاریخ پایان میلادی"),
                ),
            ],
            options={
                "verbose_name": "دوره",
                "verbose_name_plural": "دوره\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام پروژه")),
                (
                    "start_date_shamsi",
                    models.DateField(verbose_name="تاریخ شروع (شمسی)"),
                ),
                (
                    "end_date_shamsi",
                    models.DateField(verbose_name="تاریخ پایان (شمسی)"),
                ),
                (
                    "start_date_gregorian",
                    models.DateField(verbose_name="تاریخ شروع (میلادی)"),
                ),
                (
                    "end_date_gregorian",
                    models.DateField(verbose_name="تاریخ پایان (میلادی)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام واحد")),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="متراژ"
                    ),
                ),
                (
                    "price_per_meter",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="قیمت هر متر"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="قیمت نهایی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "واحد",
                "verbose_name_plural": "واحدها",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_shamsi", models.DateField(verbose_name="تاریخ شمسی")),
                ("date_gregorian", models.DateField(verbose_name="تاریخ میلادی")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="مبلغ"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("principal_deposit", "آورده"),
                            ("principal_withdrawal", "خروج از سرمایه"),
                            ("profit_accrual", "سود"),
                        ],
                        max_length=20,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "day_remaining",
                    models.IntegerField(verbose_name="روز مانده تا پایان پروژه"),
                ),
                (
                    "day_from_start",
                    models.IntegerField(verbose_name="روز از ابتدای پروژه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.investor",
                        verbose_name="سرمایه\u200cگذار",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.period",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
            },
        ),
        migrations.AddField(
            model_name="period",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.project",
                verbose_name="پروژه",
            ),
        ),
        migrations.AddField(
            model_name="investor",
            name="units",
            field=models.ManyToManyField(to="construction.unit", verbose_name="واحدها"),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("project_manager", "مدیر پروژه"),
                            ("facilities_manager", "مسئول تأسیسات"),
                            ("procurement", "کارپرداز"),
                            ("warehouse", "انباردار"),
                            ("construction_contractor", "پیمان ساختمان"),
                            ("other", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="نوع هزینه",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="مبلغ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.period",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "هزینه",
                "verbose_name_plural": "هزینه\u200cها",
            },
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("project", "year", "month_number")},
        ),
    ]
