# Generated by Django 4.2.23 on 2025-08-30 19:00

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="end_date_shamsi",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ پایان شمسی"),
        ),
        migrations.AlterField(
            model_name="period",
            name="start_date_shamsi",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ شروع شمسی"),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date_shamsi",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ پایان (شمسی)"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date_shamsi",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ شروع (شمسی)"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date_shamsi",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ شمسی"),
        ),
    ]
