# Generated by Django 4.2.23 on 2025-09-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0002_alter_period_end_date_shamsi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="day_from_start",
            field=models.IntegerField(default=0, verbose_name="روز از ابتدای پروژه"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="day_remaining",
            field=models.IntegerField(
                default=0, verbose_name="روز مانده تا پایان پروژه"
            ),
        ),
    ]
