# Generated by Django 4.2.23 on 2025-09-02 11:40

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0003_alter_transaction_day_from_start_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="مثال: 0.04819",
                        max_digits=10,
                        verbose_name="نرخ سود روزانه",
                    ),
                ),
                (
                    "effective_date",
                    django_jalali.db.models.jDateField(
                        help_text="تاریخی که این نرخ از آن اعمال می\u200cشود",
                        verbose_name="تاریخ اعمال (شمسی)",
                    ),
                ),
                (
                    "effective_date_gregorian",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ اعمال (میلادی)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="دلیل تغییر نرخ سود",
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="آیا این نرخ در حال حاضر فعال است؟",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "نرخ سود",
                "verbose_name_plural": "نرخ\u200cهای سود",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_system_generated",
            field=models.BooleanField(
                default=False,
                help_text="آیا این تراکنش توسط سیستم محاسبه شده است؟",
                verbose_name="تولید شده توسط سیستم",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="interest_rate",
            field=models.ForeignKey(
                blank=True,
                help_text="نرخ سودی که برای محاسبه این تراکنش استفاده شده",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="construction.interestrate",
                verbose_name="نرخ سود اعمال شده",
            ),
        ),
    ]
