# Generated by Django 4.2.23 on 2025-09-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0004_interestrate_transaction_is_system_generated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="parent_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="برای تراکنش\u200cهای سود: تراکنش آورده یا خروج از سرمایه مربوطه",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.transaction",
                verbose_name="تراکنش اصلی",
            ),
        ),
    ]
