# Generated by Django 4.2.23 on 2025-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0005_transaction_parent_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interestrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=7,
                help_text="مثال: 0.0004819",
                max_digits=10,
                verbose_name="نرخ سود روزانه",
            ),
        ),
    ]
