# Generated by Django 4.2.23 on 2025-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0006_alter_interestrate_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interestrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=15,
                help_text="مثال: 0.000481925679775",
                max_digits=20,
                verbose_name="نرخ سود روزانه",
            ),
        ),
    ]
