# Generated by Django 4.2.23 on 2025-09-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0008_alter_expense_id_alter_interestrate_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="آیا این پروژه در حال حاضر فعال است؟ (فقط یک پروژه می\u200cتواند فعال باشد)",
                verbose_name="پروژه فعال",
            ),
        ),
    ]
