# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='participation_type',
            field=models.CharField(
                choices=[('owner', 'مالک'), ('investor', 'سرمایه\u200cگذار')],
                default='owner',
                max_length=20,
                verbose_name='نوع مشارکت'
            ),
        ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=models.EmailField(blank=True, null=True, verbose_name='ایمیل'),
        ),
    ]
