# Generated by Django 4.2.7 on 2024-01-01 00:01

from django.db import migrations


def set_default_participation_type(apps, schema_editor):
    """
    تنظیم مقدار 'مالک' برای همه رکوردهای موجود سرمایه‌گذار
    """
    Investor = apps.get_model('construction', 'Investor')
    Investor.objects.all().update(participation_type='owner')


def reverse_set_default_participation_type(apps, schema_editor):
    """
    عملیات معکوس - نیازی به انجام کاری نیست
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_investor_participation_type_and_email_optional'),
    ]

    operations = [
        migrations.RunPython(
            set_default_participation_type,
            reverse_set_default_participation_type,
        ),
    ]
