# Generated by Django 4.2.23 on 2025-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0011_set_default_participation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor",
            name="units",
            field=models.ManyToManyField(
                blank=True, to="construction.unit", verbose_name="واحدها"
            ),
        ),
    ]
