# Generated by Django 4.2.23 on 2025-09-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0012_alter_investor_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("project_manager", "مدیر پروژه"),
                    ("facilities_manager", "سرپرست کارگاه"),
                    ("procurement", "کارپرداز"),
                    ("warehouse", "انباردار"),
                    ("construction_contractor", "پیمان ساختمان"),
                    ("other", "سایر"),
                ],
                max_length=30,
                verbose_name="نوع هزینه",
            ),
        ),
    ]
