# Generated by Django 4.2.23 on 2025-10-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0014_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="correction_factor",
            field=models.DecimalField(
                decimal_places=10,
                default=1.0,
                help_text="ضریب اصلاحی برای محاسبات پروژه",
                max_digits=20,
                verbose_name="ضریب اصلاحی",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_infrastructure",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="زیر بنای کل پروژه به متر مربع",
                max_digits=15,
                verbose_name="زیر بنای کل",
            ),
        ),
    ]
