# Generated by Django 4.2.23 on 2025-10-06 14:13

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0015_project_correction_factor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investor",
            name="contract_date_shamsi",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ قرارداد (شمسی)"
            ),
        ),
    ]
