# Generated by Django 4.2.23 on 2025-10-12 12:29

from django.db import migrations, models
import django.db.models.deletion


def populate_project_field(apps, schema_editor):
    """
    پر کردن فیلد project برای رکوردهای موجود با پروژه فعال یا اولین پروژه
    """
    Project = apps.get_model('construction', 'Project')
    Investor = apps.get_model('construction', 'Investor')
    InterestRate = apps.get_model('construction', 'InterestRate')
    
    # دریافت پروژه فعال یا اولین پروژه
    active_project = Project.objects.filter(is_active=True).first()
    if not active_project:
        active_project = Project.objects.first()
    
    # اگر پروژه‌ای وجود نداشت، migration را skip کن
    if not active_project:
        return
    
    # به‌روزرسانی Investors که project ندارند
    investors_updated = Investor.objects.filter(project__isnull=True).update(project=active_project)
    
    # به‌روزرسانی InterestRates که project ندارند
    rates_updated = InterestRate.objects.filter(project__isnull=True).update(project=active_project)
    
    # UserProfile را skip می‌کنیم چون nullable است و نیازی به مقدار پیش‌فرض ندارد
    
    print(f"✓ {investors_updated} سرمایه‌گذار به‌روزرسانی شد")
    print(f"✓ {rates_updated} نرخ سود به‌روزرسانی شد")


def reverse_populate(apps, schema_editor):
    """
    در صورت rollback، فیلدهای project را خالی می‌کنیم
    """
    Investor = apps.get_model('construction', 'Investor')
    InterestRate = apps.get_model('construction', 'InterestRate')
    
    Investor.objects.all().update(project=None)
    InterestRate.objects.all().update(project=None)


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0016_investor_contract_date_shamsi"),
    ]

    operations = [
        # بخش 1: اضافه کردن فیلدهای nullable
        migrations.AddField(
            model_name="interestrate",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="پروژه‌ای که این نرخ سود برای آن اعمال می‌شود",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.project",
                verbose_name="پروژه",
            ),
        ),
        migrations.AddField(
            model_name="investor",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="پروژه‌ای که این سرمایه‌گذار در آن مشارکت دارد",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.project",
                verbose_name="پروژه",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="پروژه‌ای که این کاربر به آن دسترسی دارد",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.project",
                verbose_name="پروژه",
            ),
        ),
        
        # بخش 2: Data Migration - پر کردن مقادیر
        migrations.RunPython(populate_project_field, reverse_populate),
        
        # بخش 3: تغییر به non-nullable (فقط برای Investor و InterestRate)
        migrations.AlterField(
            model_name="investor",
            name="project",
            field=models.ForeignKey(
                help_text="پروژه‌ای که این سرمایه‌گذار در آن مشارکت دارد",
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.project",
                verbose_name="پروژه",
            ),
        ),
        migrations.AlterField(
            model_name="interestrate",
            name="project",
            field=models.ForeignKey(
                help_text="پروژه‌ای که این نرخ سود برای آن اعمال می‌شود",
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.project",
                verbose_name="پروژه",
            ),
        ),
        # UserProfile.project همچنان nullable می‌ماند
    ]
