# Generated by Django 4.2.23 on 2025-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0017_interestrate_project_investor_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="construction_contractor_percentage",
            field=models.DecimalField(
                decimal_places=3,
                default=0.1,
                help_text="درصد پیمان ساخت از مجموع سایر هزینه\u200cها (به صورت اعشاری، مثلاً 0.100 برای 10%)",
                max_digits=6,
                verbose_name="درصد پیمان ساخت",
            ),
        ),
    ]
