# Generated by Django 4.2.23 on 2025-10-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0018_add_construction_contractor_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="area",
            field=models.DecimalField(
                decimal_places=4, max_digits=12, verbose_name="متراژ"
            ),
        ),
    ]
