# Generated by Django 4.2.23 on 2025-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0019_alter_unit_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="investor",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="توضیحات اضافی درباره این سرمایه\u200cگذار",
                null=True,
                verbose_name="توضیحات",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("principal_deposit", "آورده"),
                    ("loan_deposit", "آورده وام"),
                    ("principal_withdrawal", "خروج از سرمایه"),
                    ("profit_accrual", "سود"),
                ],
                max_length=20,
                verbose_name="نوع تراکنش",
            ),
        ),
    ]
