# Generated by Django 4.2.23 on 2025-11-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0020_investor_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="توضیحات اضافی درباره پروژه",
                null=True,
                verbose_name="توضیحات",
            ),
        ),
    ]
