# Generated by Django 4.2.23 on 2025-11-14 12:17

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0021_project_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitSpecificExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "date_shamsi",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ (شمسی)"),
                ),
                ("date_gregorian", models.DateField(verbose_name="تاریخ (میلادی)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="مبلغ"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.project",
                        verbose_name="پروژه",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.unit",
                        verbose_name="واحد",
                    ),
                ),
            ],
            options={
                "verbose_name": "هزینه اختصاصی واحد",
                "verbose_name_plural": "هزینه\u200cهای اختصاصی واحد",
                "ordering": ["-date_shamsi", "-created_at"],
            },
        ),
    ]
