# Generated by Django 4.2.23 on 2025-11-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0023_project_color_and_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_active",
        ),
    ]
