# Generated by Django 4.2.23 on 2025-11-17 15:00

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0024_remove_is_active_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="PettyCashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("project_manager", "مدیر پروژه"),
                            ("facilities_manager", "سرپرست کارگاه"),
                            ("procurement", "کارپرداز"),
                            ("warehouse", "انباردار"),
                            ("construction_contractor", "پیمان ساختمان"),
                            ("other", "سایر"),
                        ],
                        help_text="نوع هزینه که به عنوان عامل اجرایی استفاده می\u200cشود",
                        max_length=30,
                        verbose_name="عامل اجرایی",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("receipt", "دریافت تنخواه"),
                            ("return", "عودت تنخواه"),
                        ],
                        max_length=20,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="همیشه مثبت ذخیره می\u200cشود",
                        max_digits=20,
                        verbose_name="مبلغ",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="شماره فیش/رسید"
                    ),
                ),
                (
                    "date_shamsi",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ شمسی"),
                ),
                ("date_gregorian", models.DateField(verbose_name="تاریخ میلادی")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش تنخواه",
                "verbose_name_plural": "تراکنش\u200cهای تنخواه",
                "ordering": ["-date_gregorian", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "expense_type", "date_gregorian"],
                        name="constructio_project_715e45_idx",
                    )
                ],
            },
        ),
    ]
