# Generated by Django 4.2.23 on 2025-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0025_pettycashtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gradient_primary_color",
            field=models.CharField(
                default="#667eea",
                help_text="رنگ اول گرادیانت پس\u200cزمینه (فرمت HEX)",
                max_length=7,
                verbose_name="رنگ اول گرادیانت",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gradient_secondary_color",
            field=models.CharField(
                default="#764ba2",
                help_text="رنگ دوم گرادیانت پس\u200cزمینه (فرمت HEX)",
                max_length=7,
                verbose_name="رنگ دوم گرادیانت",
            ),
        ),
    ]
